In [4]:
!pip install pandas

import pandas as pd 
hello = pd.read_parquet("./labeled_sentiment.parquet")

hello

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

,doc_id,company,quarter,sentence,label,pos,neg,sentiment_score,sentence_id
0,1-800-PetMeds_10-Q_2020-01-28,1-800-PetMeds,Q1,presently the companys product line includes a...,neutral,0.000687,0.000033,0.000653,0
1,1-800-PetMeds_10-Q_2020-01-28,1-800-PetMeds,Q1,approximately NUM of all sales were generated ...,neutral,0.000033,0.000043,-0.000011,1
2,1-800-PetMeds_10-Q_2020-01-28,1-800-PetMeds,Q1,on an ongoing basis we re-evaluate our judgmen...,neutral,0.000019,0.000103,-0.000084,2
3,1-800-PetMeds_10-Q_2020-01-28,1-800-PetMeds,Q1,we base our estimates and judgments on our his...,neutral,0.000034,0.000037,-0.000004,3
4,1-800-PetMeds_10-Q_2020-01-28,1-800-PetMeds,Q1,actual results may differ from these estimates...,neutral,0.000023,0.000049,-0.000026,4
...,...,...,...,...,...,...,...,...,...
452385,reAlpha_Tech_10-Q_2025-11-12,reAlpha_Tech,Q4,to the extent that we do not generate sufficie...,neutral,0.000019,0.000056,-0.000037,452385
452386,reAlpha_Tech_10-Q_2025-11-12,reAlpha_Tech,Q4,on july NUM NUM following the closing of the N...,neutral,0.000913,0.000054,0.000860,452386
452387,reAlpha_Tech_10-Q_2025-11-12,reAlpha_Tech,Q4,with respect to the outstanding gem warrants d...,neutral,0.000020,0.000158,-0.000138,452387
452388,reAlpha_Tech_10-Q_2025-11-12,reAlpha_Tech,Q4,given the trading price of our common stock an...,neutral,0.000015,0.000072,-0.000058,452388
452389,reAlpha_Tech_10-Q_2025-11-12,reAlpha_Tech,Q4,upon such payment we fully satisfied all amoun...,neutral,0.294787,0.335366,-0.040579,452389

In [5]:
hello['label'].value_counts()

label
neutral     377900
positive     38319
negative     36171
Name: count, dtype: int64

In [7]:
pos_neg = hello.query("label != 'neutral'")
pos_neg.head(100)

,doc_id,company,quarter,sentence,label,pos,neg,sentiment_score,sentence_id
18,1-800-PetMeds_10-Q_2020-01-28,1-800-PetMeds,Q1,the decrease to other income for the quarter e...,negative,0.000073,0.999736,-0.999663,18
32,1-800-PetMeds_10-K_2020-05-26,1-800-PetMeds,Q2,due to covid- NUM consumer demand has increase...,positive,0.999299,0.000111,0.999188,32
41,1-800-PetMeds_10-K_2020-05-26,1-800-PetMeds,Q2,the decrease to the income tax provision for f...,negative,0.000052,0.999468,-0.999416,41
52,1-800-PetMeds_10-Q_2020-08-03,1-800-PetMeds,Q3,approximately NUM of the increase to general a...,positive,0.999379,0.000196,0.999182,52
54,1-800-PetMeds_10-Q_2020-08-03,1-800-PetMeds,Q3,the increase in the income tax provision for t...,positive,0.999530,0.000160,0.999370,54
...,...,...,...,...,...,...,...,...,...
629,3D_Systems_10-Q_2016-08-03,3D_Systems,Q3,gross profit margin for materials decreased f ...,negative,0.000063,0.999444,-0.999381,629
630,3D_Systems_10-Q_2016-08-03,3D_Systems,Q3,gross prof it margin for services decreased fo...,negative,0.000086,0.999726,-0.999640,630
636,3D_Systems_10-Q_2016-08-03,3D_Systems,Q3,days sales outstanding was NUM days at june NU...,negative,0.000104,0.999625,-0.999521,636
646,3D_Systems_10-Q_2016-11-03,3D_Systems,Q4,for the quarter ended september NUM NUM s oftw...,positive,0.998392,0.000101,0.998290,646
648,3D_Systems_10-Q_2016-11-03,3D_Systems,Q4,due to the relatively high price of certain 3d...,positive,0.999561,0.000209,0.999352,648